# Generated by Django 5.0 on 2023-12-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lugx_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
