# Generated by Django 5.0 on 2023-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lugx_site", "0002_product_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="total_searched",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_plays",
            field=models.IntegerField(default=0),
        ),
    ]
