# Generated by Django 5.0 on 2024-03-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lugx_site", "0003_category_total_searched_product_total_plays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("total_searched", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="lugx_site.tags"),
        ),
    ]
